console.log("sagar")
console.log(2+3)
console.log("sagar")
console.log(2+3)
console.log("sagar")
console.log(2+3)

console.log("sagar")
console.log(2+3)
console.log("sagar")
console.log(2+3)
console.log("sagar")
console.log(2+3)
console.log("sagar")
console.log(2+3)